apiVersion: v1
kind: Service
metadata:
  name: webrtc-frontend-service
  namespace: webrtc
spec:
  type: LoadBalancer
  selector:
    app: webrtc-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-signaling-service
  namespace: webrtc
spec:
  type: LoadBalancer
  selector:
    app: webrtc-signaling
  ports:
    - name: signaling
      port: 3001
      targetPort: 3001
