apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-frontend
  namespace: webrtc
  labels:
    app: webrtc-frontend
    app.kubernetes.io/name: webrtc-frontend
    app.kubernetes.io/part-of: docker-advanced-webrtc-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-frontend
  template:
    metadata:
      labels:
        app: webrtc-frontend
        app.kubernetes.io/name: webrtc-frontend
        app.kubernetes.io/part-of: docker-advanced-webrtc-vue
    spec:
      containers:
        - name: frontend
          image: edumgt/webrtc-frontend:latest
          imagePullPolicy: Always
          env:
            - name: VITE_SIGNAL_URL
              value: "ws://a16745688227442f8827d9802e109290-1655988714.ap-northeast-2.elb.amazonaws.com:3001"
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
